# Generated by Django 5.2 on 2025-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='listing_type',
            field=models.CharField(choices=[('local', 'Local Listing'), ('imported', 'Imported Car'), ('sell_behalf', 'Sell on Behalf'), ('auction', 'Auctioned')], default='local', max_length=20),
        ),
    ]
