# Generated by Django 5.2 on 2025-07-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_quotation', 'On Quotation'), ('processing', 'Processing'), ('fee_paid', 'Fee Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
