# Generated by Django 5.2 on 2025-07-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_car_brand_name_car_condition_name_car_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sparepartcategory',
            unique_together={('name', 'parent')},
        ),
    ]
