# Generated by Django 5.2 on 2025-07-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_messageanalytics_messageread_messageschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='import_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.importorder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order'),
        ),
    ]
