# Generated by Django 5.2 on 2025-07-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_importorderlocation_importorderroute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorder',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
