# Generated by Django 5.2 on 2025-07-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_chassis_number_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='core.vendor'),
        ),
    ]
