# Generated by Django 5.2 on 2025-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fix_duplicate_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address must be unique', max_length=254, unique=True),
        ),
    ]
