# Generated by Django 5.2 on 2025-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_fix_empty_order_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='area',
            field=models.CharField(blank=True, help_text='Specific area/neighborhood where the car is located', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, help_text='City where the car is located', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the car is located', max_length=100),
        ),
    ]
