# Generated by Django 5.2 on 2025-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bookmark_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of bookmarks'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='breaking_news',
            field=models.BooleanField(default=False, help_text='Mark as breaking news'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of approved comments'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='news_location',
            field=models.CharField(blank=True, help_text='Location where news occurred', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='news_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], help_text='News priority level', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='news_source',
            field=models.CharField(blank=True, help_text='Source of the news article', max_length=200),
        ),
    ]
