# Generated by Django 5.2 on 2025-07-19 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_enhanced_resource_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['order', '-is_primary', '-created_at']},
        ),
        migrations.AddField(
            model_name='carimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Set as primary gallery image'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='carimage',
            index=models.Index(fields=['car', 'is_primary'], name='core_carima_car_id_245aae_idx'),
        ),
        migrations.AddIndex(
            model_name='carimage',
            index=models.Index(fields=['car', 'order'], name='core_carima_car_id_3124e9_idx'),
        ),
    ]
