# Generated by Django 5.2 on 2025-07-27 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_enhance_car_image_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('admin_reply', 'Admin Reply'), ('customer_reply', 'Customer Reply'), ('system_note', 'System Note'), ('status_change', 'Status Change'), ('assignment', 'Assignment Change'), ('escalation', 'Escalation')], max_length=20)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note not visible to customer')),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inquiry_attachments/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='admin_response',
            field=models.TextField(blank=True, help_text="Admin's response to the inquiry"),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='customer_feedback',
            field=models.TextField(blank=True, help_text='Customer feedback on resolution'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='customer_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='customer_rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Customer satisfaction rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use only'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='requires_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes about how the inquiry was resolved'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='resolution_time_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Hours to resolution', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='response_time_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Hours to first response', null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('car', 'Car Inquiry'), ('spare_part', 'Spare Part Inquiry'), ('import', 'Import Inquiry'), ('general', 'General Inquiry'), ('support', 'Technical Support'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer Response'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'priority'], name='core_inquir_status_984059_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['assigned_admin', 'status'], name='core_inquir_assigne_2d3949_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['customer', 'status'], name='core_inquir_custome_fe16db_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['created_at'], name='core_inquir_created_86bbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['is_urgent', 'status'], name='core_inquir_is_urge_e3630c_idx'),
        ),
        migrations.AddField(
            model_name='inquiryresponse',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.inquiry'),
        ),
        migrations.AddField(
            model_name='inquiryresponse',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
