# Generated by Django 5.2 on 2025-08-05 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Make description and history')),
                ('country_of_origin', models.CharField(blank=True, help_text='Country where make originated', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='makes/')),
                ('logo_url', models.URLField(blank=True, help_text='Alternative logo URL if not uploaded')),
                ('website', models.URLField(blank=True, help_text='Official make website')),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Mark as premium/luxury make')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='compatible_brands',
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['make__name', 'name']},
        ),
        migrations.RenameField(
            model_name='importorder',
            old_name='brand',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='importrequest',
            old_name='brand',
            new_name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='car',
            name='make_name',
            field=models.CharField(blank=True, help_text='Make name when not using database makes', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carmake'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.carmake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='compatible_makes',
            field=models.ManyToManyField(blank=True, to='core.carmake'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('make', 'name')},
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
    ]
